/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Aliaksandr_Zhukovich' at '1/31/17 12:13 PM' with Gradle 3.0
 *
 * @author Aliaksandr_Zhukovich, @date 1/31/17 12:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
